// Decompiled with JetBrains decompiler
// Type: MapInfo.Commands.WindowCommands
// Assembly: MapInfo.Controls.RT, Version=17.0.0.73, Culture=neutral, PublicKeyToken=1c8d81d2ee78b75d
// MVID: BC0BD24C-3BE6-48BB-A804-29FA3B53532D
// Assembly location: C:\Program Files\MapInfo\Runtime\MapInfo.Controls.RT.dll

using MapInfo.Controls.Properties;
using System.Windows.Input;

namespace MapInfo.Commands
{
  public static class WindowCommands
  {
    private static readonly MapBasicRunMenuCommand StatisticsWindowCopyCommand;
    private static readonly MapBasicRunMenuCommand NewBrowserWindowCommand;
    private static readonly MapBasicRunMenuCommand NewMapWindowCommand;
    private static readonly MapBasicRunMenuCommand NewLayoutWindowCommand;
    private static readonly MapBasicRunMenuCommand ThreeDWindowCommand;
    private static readonly MapBasicRunMenuCommand PrismWindowCommand;
    private static readonly MapBasicRunMenuCommand MapBasicWindowCommand;
    private static readonly MapBasicRunMenuCommand StatisticsWindowCommand;
    private static readonly MapBasicRunMenuCommand LegendWindowCommand;
    private static readonly MapBasicRunMenuCommand RedistrictWindowCommand;
    private static readonly MapBasicRunMenuCommand RedrawWindowCommand;
    private static readonly MapBasicRunMenuCommand RecoverWindowsCommand;
    private static readonly MapBasicRunMenuCommand CloneWindowCommand;
    private static readonly MapBasicRunMenuCommand CustomColorsCommand;
    private static readonly MapBasicRunMenuCommand InfoWindowCommand;
    private static readonly MapBasicRunMenuCommand MessageWindowCommand;
    private static readonly MapBasicRunMenuCommand RulerWindowCommand;
    private static readonly MapBasicRunMenuCommand WindowListCommand;
    private static readonly MapBasicRunMenuCommand ToolManagerCommand;
    private static readonly MapBasicRunMenuCommand TaskManagerCommand;
    private static readonly MapBasicRunMenuCommand ConnectionListCommand;
    private static readonly MapBasicRunMenuCommand ClearMsgWinCommand;
    private static readonly MapBasicRunMenuCommand LayerControlCommand;
    private static readonly MapBasicRunMenuCommand TableListCommand;
    private static readonly MapBasicRunMenuCommand WorkspaceExplorerCommand;
    private static readonly MapBasicRunMenuCommand StatusBarWindowCommand;

    static WindowCommands()
    {
      MapBasicRunMenuCommand basicRunMenuCommand1 = new MapBasicRunMenuCommand(621, nameof (ClearMsgWin), (InputGestureCollection) null);
      basicRunMenuCommand1.Text = Resources.Command_ClearMsgWin_Label;
      basicRunMenuCommand1.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Application/clearMapbasicWindow_16x16.png";
      basicRunMenuCommand1.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Application/clearMapbasicWindow_32x32.png";
      basicRunMenuCommand1.ToolTipDescription = Resources.Command_ClearMsgWin_ToolTip_Description;
      basicRunMenuCommand1.ToolTipText = Resources.Command_ClearMsgWin_ToolTip_Text;
      basicRunMenuCommand1.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand1.EnableCommand = false;
      basicRunMenuCommand1.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.ClearMsgWinCommand = basicRunMenuCommand1;
      WindowCommands.ClearMsgWinCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand2 = new MapBasicRunMenuCommand(608, nameof (MapBasicWindow), MapInfoCommand.GetGesture(Resources.Command_MapBasicWindow_KeyGesture));
      basicRunMenuCommand2.Text = Resources.Command_MapBasicWindow_Label;
      basicRunMenuCommand2.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/mapbasicWindow_16x16.png";
      basicRunMenuCommand2.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/mapbasicWindow_32x32.png";
      basicRunMenuCommand2.ToolTipDescription = Resources.Command_MapBasicWindow_ToolTip_Description;
      basicRunMenuCommand2.ToolTipText = Resources.Command_MapBasicWindow_ToolTip_Text;
      basicRunMenuCommand2.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand2.EnableCommand = true;
      basicRunMenuCommand2.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.MapBasicWindowCommand = basicRunMenuCommand2;
      WindowCommands.MapBasicWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand3 = new MapBasicRunMenuCommand(616, nameof (StatusBarWindow), (InputGestureCollection) null);
      basicRunMenuCommand3.Text = Resources.Command_StatusBarWindow_Label;
      basicRunMenuCommand3.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/statusBar_16x16.png";
      basicRunMenuCommand3.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/statusBar_32X32.png";
      basicRunMenuCommand3.ToolTipDescription = Resources.Command_StatusBarWindow_ToolTip_Description;
      basicRunMenuCommand3.ToolTipText = Resources.Command_StatusBarWindow_ToolTip_Text;
      basicRunMenuCommand3.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand3.EnableCommand = true;
      basicRunMenuCommand3.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.StatusBarWindowCommand = basicRunMenuCommand3;
      WindowCommands.StatusBarWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand4 = new MapBasicRunMenuCommand(836, nameof (StatisticsWindow), MapInfoCommand.GetGesture(Resources.Command_StatisticsWindow_KeyGesture));
      basicRunMenuCommand4.Text = Resources.Command_StatisticsWindow_Label;
      basicRunMenuCommand4.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/statsWindow_16x16.png";
      basicRunMenuCommand4.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/statsWindow_32x32.png";
      basicRunMenuCommand4.ToolTipDescription = Resources.Command_StatisticsWindow_ToolTip_Description;
      basicRunMenuCommand4.ToolTipText = Resources.Command_StatisticsWindow_ToolTip_Text;
      basicRunMenuCommand4.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand4.EnableCommand = true;
      basicRunMenuCommand4.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.StatisticsWindowCommand = basicRunMenuCommand4;
      WindowCommands.StatisticsWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand5 = new MapBasicRunMenuCommand(844, nameof (LegendWindow), MapInfoCommand.GetGesture(Resources.Command_LegendWindow_KeyGesture));
      basicRunMenuCommand5.Text = Resources.Command_LegendWindow_Label;
      basicRunMenuCommand5.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/themeLegend_16x16.png";
      basicRunMenuCommand5.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/themeLegend_32x32.png";
      basicRunMenuCommand5.ToolTipDescription = Resources.Command_LegendWindow_ToolTip_Description;
      basicRunMenuCommand5.ToolTipText = Resources.Command_LegendWindow_ToolTip_Text;
      basicRunMenuCommand5.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand5.EnableCommand = true;
      basicRunMenuCommand5.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.LegendWindowCommand = basicRunMenuCommand5;
      WindowCommands.LegendWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand6 = new MapBasicRunMenuCommand(615, "RedistricterWindow", MapInfoCommand.GetGesture(Resources.Command_RedistricterWindow_KeyGesture));
      basicRunMenuCommand6.Text = Resources.Command_RedistricterWindow_Label;
      basicRunMenuCommand6.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/redistricter_16x16.png";
      basicRunMenuCommand6.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/redistricter_32x32.png";
      basicRunMenuCommand6.ToolTipDescription = Resources.Command_RedistricterWindow_ToolTip_Description;
      basicRunMenuCommand6.ToolTipText = Resources.Command_RedistricterWindow_ToolTip_Text;
      basicRunMenuCommand6.ToolTipDisabledText = Resources.Command_Disabled_Redistricter;
      basicRunMenuCommand6.EnableCommand = false;
      basicRunMenuCommand6.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.RedistrictWindowCommand = basicRunMenuCommand6;
      WindowCommands.RedistrictWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand7 = new MapBasicRunMenuCommand(601, nameof (NewBrowserWindow), MapInfoCommand.GetGesture(Resources.Command_NewBrowserWindow_KeyGesture));
      basicRunMenuCommand7.Text = Resources.Command_NewBrowserWindow_Label;
      basicRunMenuCommand7.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/newBrowser_16x16.png";
      basicRunMenuCommand7.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/newBrowser_32x32.png";
      basicRunMenuCommand7.ToolTipDescription = Resources.Command_NewBrowserWindow_ToolTip_Description;
      basicRunMenuCommand7.ToolTipText = Resources.Command_NewBrowserWindow_ToolTip_Text;
      basicRunMenuCommand7.ToolTipDisabledText = Resources.Command_Disabled_NeedOpenTable;
      basicRunMenuCommand7.EnableCommand = false;
      basicRunMenuCommand7.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.NewBrowserWindowCommand = basicRunMenuCommand7;
      WindowCommands.NewBrowserWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand8 = new MapBasicRunMenuCommand(617, nameof (CustomColors), (InputGestureCollection) null);
      basicRunMenuCommand8.Text = Resources.Command_CustomColors_Label;
      basicRunMenuCommand8.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/customColors_16x16.png";
      basicRunMenuCommand8.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/customColors_32x32.png";
      basicRunMenuCommand8.ToolTipDescription = Resources.Command_CustomColors_ToolTip_Description;
      basicRunMenuCommand8.ToolTipText = Resources.Command_CustomColors_ToolTip_Text;
      basicRunMenuCommand8.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand8.EnableCommand = true;
      basicRunMenuCommand8.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.CustomColorsCommand = basicRunMenuCommand8;
      WindowCommands.CustomColorsCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand9 = new MapBasicRunMenuCommand(602, nameof (NewMapWindow), MapInfoCommand.GetGesture(Resources.Command_NewMapWindow_KeyGesture));
      basicRunMenuCommand9.Text = Resources.Command_NewMapWindow_Label;
      basicRunMenuCommand9.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/newMap_16x16.png";
      basicRunMenuCommand9.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/newMap_32x32.png";
      basicRunMenuCommand9.ToolTipDescription = Resources.Command_NewMapWindow_ToolTip_Description;
      basicRunMenuCommand9.ToolTipText = Resources.Command_NewMapWindow_ToolTip_Text;
      basicRunMenuCommand9.ToolTipDisabledText = Resources.Command_Disabled_NeedOpenTable;
      basicRunMenuCommand9.EnableCommand = false;
      basicRunMenuCommand9.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.NewMapWindowCommand = basicRunMenuCommand9;
      WindowCommands.NewMapWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand10 = new MapBasicRunMenuCommand(620, nameof (NewLayoutWindow), MapInfoCommand.GetGesture(Resources.Command_NewLayoutWindow_KeyGesture));
      basicRunMenuCommand10.Text = Resources.Command_NewLayoutWindow_Label;
      basicRunMenuCommand10.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Layout/newLayoutPage_16x16.png";
      basicRunMenuCommand10.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Layout/newLayoutPage_32x32.png";
      basicRunMenuCommand10.ToolTipDescription = Resources.Command_NewLayoutWindow_ToolTip_Description;
      basicRunMenuCommand10.ToolTipText = Resources.Command_NewLayoutWindow_ToolTip_Text;
      basicRunMenuCommand10.ToolTipDisabledText = Resources.Command_Disabled_NeedOpenTable;
      basicRunMenuCommand10.EnableCommand = true;
      basicRunMenuCommand10.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.NewLayoutWindowCommand = basicRunMenuCommand10;
      WindowCommands.NewLayoutWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand11 = new MapBasicRunMenuCommand(817, nameof (ThreeDWindow), MapInfoCommand.GetGesture(Resources.Command_3DWindow_KeyGesture));
      basicRunMenuCommand11.Text = Resources.Command_ThreeDWindow_Label;
      basicRunMenuCommand11.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/new3DMap_16x16.png";
      basicRunMenuCommand11.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/new3DMap_32x32.png";
      basicRunMenuCommand11.ToolTipDescription = Resources.Command_ThreeDWindow_ToolTip_Description;
      basicRunMenuCommand11.ToolTipText = Resources.Command_ThreeDWindow_ToolTip_Text;
      basicRunMenuCommand11.ToolTipDisabledText = Resources.Command_Disabled_ThreeDWindow;
      basicRunMenuCommand11.EnableCommand = false;
      basicRunMenuCommand11.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.ThreeDWindowCommand = basicRunMenuCommand11;
      WindowCommands.ThreeDWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand12 = new MapBasicRunMenuCommand(818, nameof (PrismWindow), MapInfoCommand.GetGesture(Resources.Command_PrismWindow_KeyGesture));
      basicRunMenuCommand12.Text = Resources.Command_PrismWindow_Label;
      basicRunMenuCommand12.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/newPrismMap_16x16.png";
      basicRunMenuCommand12.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/newPrismMap_32x32.png";
      basicRunMenuCommand12.ToolTipDescription = Resources.Command_PrismWindow_ToolTip_Description;
      basicRunMenuCommand12.ToolTipText = Resources.Command_PrismWindow_ToolTip_Text;
      basicRunMenuCommand12.ToolTipDisabledText = Resources.Command_Disabled_PrismWindow;
      basicRunMenuCommand12.EnableCommand = false;
      basicRunMenuCommand12.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.PrismWindowCommand = basicRunMenuCommand12;
      WindowCommands.PrismWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand13 = new MapBasicRunMenuCommand(610, nameof (RedrawWindow), MapInfoCommand.GetGesture(Resources.Command_RedrawWindow_KeyGesture));
      basicRunMenuCommand13.Text = Resources.Command_RedrawWindow_Label;
      basicRunMenuCommand13.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/redrawWindows_16x16.png";
      basicRunMenuCommand13.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/redrawWindows_32x32.png";
      basicRunMenuCommand13.ToolTipDescription = Resources.Command_RedrawWindow_ToolTip_Description;
      basicRunMenuCommand13.ToolTipText = Resources.Command_RedrawWindow_ToolTip_Text;
      basicRunMenuCommand13.ToolTipDisabledText = Resources.Command_Disabled_NeedFrontDocumentWindow;
      basicRunMenuCommand13.EnableCommand = false;
      basicRunMenuCommand13.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.RedrawWindowCommand = basicRunMenuCommand13;
      WindowCommands.RedrawWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand14 = new MapBasicRunMenuCommand(619, nameof (RecoverWindows), (InputGestureCollection) null);
      basicRunMenuCommand14.Text = Resources.Command_RecoverWindows_Label;
      basicRunMenuCommand14.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/recoverWindows_16x16.png";
      basicRunMenuCommand14.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/recoverWindows_32x32.png";
      basicRunMenuCommand14.ToolTipDescription = Resources.Command_RecoverWindows_ToolTip_Description;
      basicRunMenuCommand14.ToolTipText = Resources.Command_RecoverWindows_ToolTip_Text;
      basicRunMenuCommand14.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand14.EnableCommand = true;
      basicRunMenuCommand14.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.RecoverWindowsCommand = basicRunMenuCommand14;
      WindowCommands.RecoverWindowsCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand15 = new MapBasicRunMenuCommand(834, nameof (InfoWindow), MapInfoCommand.GetGesture(Resources.Command_InfoWindow_KeyGesture));
      basicRunMenuCommand15.Text = Resources.Command_InfoWindow_Label;
      basicRunMenuCommand15.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/infoTool_16x16.png";
      basicRunMenuCommand15.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/infoTool_32x32.png";
      basicRunMenuCommand15.ToolTipDescription = Resources.Command_InfoWindow_ToolTip_Description;
      basicRunMenuCommand15.ToolTipText = Resources.Command_InfoWindow_ToolTip_Text;
      basicRunMenuCommand15.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand15.EnableCommand = true;
      basicRunMenuCommand15.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.InfoWindowCommand = basicRunMenuCommand15;
      WindowCommands.InfoWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand16 = new MapBasicRunMenuCommand(835, nameof (MessageWindow), (InputGestureCollection) null);
      basicRunMenuCommand16.Text = Resources.Command_MessageWindow_Label;
      basicRunMenuCommand16.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/messageWindow_16x16.png";
      basicRunMenuCommand16.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/messageWindow_32x32.png";
      basicRunMenuCommand16.ToolTipDescription = Resources.Command_MessageWindow_ToolTip_Description;
      basicRunMenuCommand16.ToolTipText = Resources.Command_MessageWindow_ToolTip_Text;
      basicRunMenuCommand16.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand16.EnableCommand = true;
      basicRunMenuCommand16.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.MessageWindowCommand = basicRunMenuCommand16;
      WindowCommands.MessageWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand17 = new MapBasicRunMenuCommand(837, nameof (RulerWindow), (InputGestureCollection) null);
      basicRunMenuCommand17.Text = Resources.Command_RulerWindow_Label;
      basicRunMenuCommand17.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/ruler_16x16.png";
      basicRunMenuCommand17.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/ruler_32x32.png";
      basicRunMenuCommand17.ToolTipDescription = Resources.Command_RulerWindow_ToolTip_Description;
      basicRunMenuCommand17.ToolTipText = Resources.Command_RulerWindow_ToolTip_Text;
      basicRunMenuCommand17.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand17.EnableCommand = true;
      basicRunMenuCommand17.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.RulerWindowCommand = basicRunMenuCommand17;
      WindowCommands.RulerWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand18 = new MapBasicRunMenuCommand(830, nameof (WindowList), MapInfoCommand.GetGesture(Resources.Command_WindowList_KeyGesture));
      basicRunMenuCommand18.Text = Resources.Command_WindowList_Label;
      basicRunMenuCommand18.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/windowList_16x16.png";
      basicRunMenuCommand18.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/windowList_32x32.png";
      basicRunMenuCommand18.ToolTipDescription = Resources.Command_WindowList_ToolTip_Description;
      basicRunMenuCommand18.ToolTipText = Resources.Command_WindowList_ToolTip_Text;
      basicRunMenuCommand18.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand18.EnableCommand = true;
      basicRunMenuCommand18.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.WindowListCommand = basicRunMenuCommand18;
      WindowCommands.WindowListCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand19 = new MapBasicRunMenuCommand(831, nameof (ToolManager), MapInfoCommand.GetGesture(Resources.Command_ToolManager_KeyGesture));
      basicRunMenuCommand19.Text = Resources.Command_ToolManager_Label;
      basicRunMenuCommand19.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/toolManager_16x16.png";
      basicRunMenuCommand19.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/toolManager_32x32.png";
      basicRunMenuCommand19.ToolTipDescription = Resources.Command_ToolManager_ToolTip_Description;
      basicRunMenuCommand19.ToolTipText = Resources.Command_ToolManager_ToolTip_Text;
      basicRunMenuCommand19.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand19.EnableCommand = true;
      basicRunMenuCommand19.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.ToolManagerCommand = basicRunMenuCommand19;
      WindowCommands.ToolManagerCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand20 = new MapBasicRunMenuCommand(832, nameof (TaskManager), MapInfoCommand.GetGesture(Resources.Command_TaskManager_KeyGesture));
      basicRunMenuCommand20.Text = Resources.Command_TaskManager_Label;
      basicRunMenuCommand20.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/tasksWindow_16x16.png";
      basicRunMenuCommand20.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/tasksWindow_32x32.png";
      basicRunMenuCommand20.ToolTipDescription = Resources.Command_TaskManager_ToolTip_Description;
      basicRunMenuCommand20.ToolTipText = Resources.Command_TaskManager_ToolTip_Text;
      basicRunMenuCommand20.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand20.EnableCommand = true;
      basicRunMenuCommand20.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.TaskManagerCommand = basicRunMenuCommand20;
      WindowCommands.TaskManagerCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand21 = new MapBasicRunMenuCommand(833, nameof (ConnectionList), (InputGestureCollection) null);
      basicRunMenuCommand21.Text = Resources.Command_ConnectionList_Label;
      basicRunMenuCommand21.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/connectionsWindow_16x16.png";
      basicRunMenuCommand21.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/connectionsWindow_32x32.png";
      basicRunMenuCommand21.ToolTipDescription = Resources.Command_ConnectionList_ToolTip_Description;
      basicRunMenuCommand21.ToolTipText = Resources.Command_ConnectionList_ToolTip_Text;
      basicRunMenuCommand21.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand21.EnableCommand = true;
      basicRunMenuCommand21.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.ConnectionListCommand = basicRunMenuCommand21;
      WindowCommands.ConnectionListCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand22 = new MapBasicRunMenuCommand(1738, nameof (TableList), MapInfoCommand.GetGesture(Resources.Command_TableList_KeyGesture));
      basicRunMenuCommand22.Text = Resources.Command_TableList_Label;
      basicRunMenuCommand22.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/tableList_16x16.png";
      basicRunMenuCommand22.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/TableList_32x32.png";
      basicRunMenuCommand22.ToolTipDescription = Resources.Command_TableList_ToolTip_Description;
      basicRunMenuCommand22.ToolTipText = Resources.Command_TableList_ToolTip_Text;
      basicRunMenuCommand22.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand22.EnableCommand = true;
      basicRunMenuCommand22.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.TableListCommand = basicRunMenuCommand22;
      WindowCommands.TableListCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand23 = new MapBasicRunMenuCommand(822, nameof (LayerControl), MapInfoCommand.GetGesture(Resources.Command_LayerControl_KeyGesture));
      basicRunMenuCommand23.Text = Resources.Command_LayerControl_Label;
      basicRunMenuCommand23.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/layerControl_16x16.png";
      basicRunMenuCommand23.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/layerControl_32x32.png";
      basicRunMenuCommand23.ToolTipDescription = Resources.Command_LayerControl_ToolTip_Description;
      basicRunMenuCommand23.ToolTipText = Resources.Command_LayerControl_ToolTip_Text;
      basicRunMenuCommand23.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand23.EnableCommand = true;
      basicRunMenuCommand23.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.LayerControlCommand = basicRunMenuCommand23;
      WindowCommands.LayerControlCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand24 = new MapBasicRunMenuCommand(829, nameof (WorkspaceExplorer), MapInfoCommand.GetGesture(Resources.Command_WorkspaceExplorer_KeyGesture));
      basicRunMenuCommand24.Text = Resources.Command_WorkspaceExplorer_Label;
      basicRunMenuCommand24.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/workspaceExplorerWindow_16x16.png";
      basicRunMenuCommand24.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Window/workspaceExplorerWindow_32x32.png";
      basicRunMenuCommand24.ToolTipDescription = Resources.Command_WorkspaceExplorer_ToolTip_Description;
      basicRunMenuCommand24.ToolTipText = Resources.Command_WorkspaceExplorer_ToolTip_Text;
      basicRunMenuCommand24.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand24.EnableCommand = true;
      basicRunMenuCommand24.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.WorkspaceExplorerCommand = basicRunMenuCommand24;
      WindowCommands.WorkspaceExplorerCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand25 = new MapBasicRunMenuCommand(622, nameof (CloneWindow), MapInfoCommand.GetGesture(Resources.Command_CloneWindow_KeyGesture));
      basicRunMenuCommand25.Text = Resources.Command_CloneWindow_Label;
      basicRunMenuCommand25.MenuItemText = Resources.Command_CloneWindow_MenuItemText;
      basicRunMenuCommand25.SmallIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/CloneMap_16x16.png";
      basicRunMenuCommand25.LargeIcon = "pack://application:,,,/MapInfo.StyleResources;component/Images/Mapping/CloneMap_32x32.png";
      basicRunMenuCommand25.ToolTipDescription = Resources.Command_CloneWindow_ToolTip_Description;
      basicRunMenuCommand25.ToolTipText = Resources.Command_CloneWindow_ToolTip_Text;
      basicRunMenuCommand25.ToolTipDisabledText = Resources.Command_NeedCloneableWindow;
      basicRunMenuCommand25.EnableCommand = true;
      basicRunMenuCommand25.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.CloneWindowCommand = basicRunMenuCommand25;
      WindowCommands.CloneWindowCommand.CreateScreenTip();
      MapBasicRunMenuCommand basicRunMenuCommand26 = new MapBasicRunMenuCommand(2301, nameof (StatisticsWindowCopy), MapInfoCommand.GetGesture(Resources.Command_StatisticsWindowCopy_KeyGesture));
      basicRunMenuCommand26.Text = Resources.Command_StatisticsWindowCopy_Label;
      basicRunMenuCommand26.MenuItemText = Resources.Command_StatisticsWindowCopy_MenuText;
      basicRunMenuCommand26.ToolTipDescription = Resources.Command_StatisticsWindowCopy_ToolTip_Description;
      basicRunMenuCommand26.ToolTipText = Resources.Command_StatisticsWindowCopy_ToolTip_Text;
      basicRunMenuCommand26.ToolTipDisabledText = Resources.Command_AlwaysEnabled;
      basicRunMenuCommand26.EnableCommand = false;
      basicRunMenuCommand26.Category = Resources.Command_Category_WindowCommands;
      WindowCommands.StatisticsWindowCopyCommand = basicRunMenuCommand26;
      WindowCommands.StatisticsWindowCopyCommand.CreateScreenTip();
    }

    public static MapInfoCommand ClearMsgWin => (MapInfoCommand) WindowCommands.ClearMsgWinCommand;
    public static MapInfoCommand MapBasicWindow => (MapInfoCommand) WindowCommands.MapBasicWindowCommand;
    public static MapInfoCommand StatisticsWindow => (MapInfoCommand) WindowCommands.StatisticsWindowCommand;
    public static MapInfoCommand LegendWindow => (MapInfoCommand) WindowCommands.LegendWindowCommand;
    public static MapInfoCommand RedistrictWindow => (MapInfoCommand) WindowCommands.RedistrictWindowCommand;
    public static MapInfoCommand NewBrowserWindow => (MapInfoCommand) WindowCommands.NewBrowserWindowCommand;
    public static MapInfoCommand NewMapWindow => (MapInfoCommand) WindowCommands.NewMapWindowCommand;
    public static MapInfoCommand NewLayoutWindow => (MapInfoCommand) WindowCommands.NewLayoutWindowCommand;
    public static MapInfoCommand ThreeDWindow => (MapInfoCommand) WindowCommands.ThreeDWindowCommand;
    public static MapInfoCommand PrismWindow => (MapInfoCommand) WindowCommands.PrismWindowCommand;
    public static MapInfoCommand RecoverWindows => (MapInfoCommand) WindowCommands.RecoverWindowsCommand;
    public static MapInfoCommand CloneWindow => (MapInfoCommand) WindowCommands.CloneWindowCommand;
    public static MapInfoCommand RedrawWindow => (MapInfoCommand) WindowCommands.RedrawWindowCommand;
    public static MapInfoCommand InfoWindow => (MapInfoCommand) WindowCommands.InfoWindowCommand;
    public static MapInfoCommand MessageWindow => (MapInfoCommand) WindowCommands.MessageWindowCommand;
    public static MapInfoCommand RulerWindow => (MapInfoCommand) WindowCommands.RulerWindowCommand;
    public static MapInfoCommand WindowList => (MapInfoCommand) WindowCommands.WindowListCommand;
    public static MapInfoCommand ToolManager => (MapInfoCommand) WindowCommands.ToolManagerCommand;
    public static MapInfoCommand TaskManager => (MapInfoCommand) WindowCommands.TaskManagerCommand;
    public static MapInfoCommand ConnectionList => (MapInfoCommand) WindowCommands.ConnectionListCommand;
    public static MapInfoCommand LayerControl => (MapInfoCommand) WindowCommands.LayerControlCommand;
    public static MapInfoCommand TableList => (MapInfoCommand) WindowCommands.TableListCommand;
    public static MapInfoCommand WorkspaceExplorer => (MapInfoCommand) WindowCommands.WorkspaceExplorerCommand;
    public static MapInfoCommand CustomColors =>  (MapInfoCommand) WindowCommands.CustomColorsCommand;
    public static MapInfoCommand StatusBarWindow => (MapInfoCommand) WindowCommands.StatusBarWindowCommand;
    public static MapInfoCommand StatisticsWindowCopy => (MapInfoCommand) WindowCommands.StatisticsWindowCopyCommand;
    
    internal static MapBasicRunMenuCommand CreateCommand(
      string desc,
      string name,
      int id,
      InputGesture keyGesture)
    {
      InputGestureCollection inputGestureCollection = new InputGestureCollection();
      if (keyGesture != null)
        inputGestureCollection.Add(keyGesture);
      return new MapBasicRunMenuCommand(id, name, inputGestureCollection);
    }
  }
}
